# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg)
  Vane_config = dbg
  VaneEditor_config = dbg
  Sandbox_config = dbg
endif
ifeq ($(config),rel)
  Vane_config = rel
  VaneEditor_config = rel
  Sandbox_config = rel
endif

PROJECTS := Vane VaneEditor Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Vane:
ifneq (,$(Vane_config))
	@echo "==== Building Vane ($(Vane_config)) ===="
	@${MAKE} --no-print-directory -C Vane -f Makefile config=$(Vane_config)
endif

VaneEditor: Vane
ifneq (,$(VaneEditor_config))
	@echo "==== Building VaneEditor ($(VaneEditor_config)) ===="
	@${MAKE} --no-print-directory -C VaneEditor -f Makefile config=$(VaneEditor_config)
endif

Sandbox: Vane
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Vane -f Makefile clean
	@${MAKE} --no-print-directory -C VaneEditor -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg"
	@echo "  rel"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Vane"
	@echo "   VaneEditor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"